"""
Django settings for mediskin project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR.parent / 'frontend'

# Load environment variables from .env — override=True ensures .env always wins
# over any stale values left in the environment from previous server runs.
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-m-syij1__7g1%%%c5p%7wf44ky604eqkf8a0e6rq$1g&)p_$q-'  # fallback for dev
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',         # required by allauth
    'corsheaders',                  # CORS support for frontend-backend API calls
    'main',
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Required by django.contrib.sites and allauth
# Site id=2 → 127.0.0.1:8000 (local dev). Change to 1 (example.com) in production.
SITE_ID = 2


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS support (must be before CommonMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # required by allauth >=0.56
]

ROOT_URLCONF = 'mediskin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mediskin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [FRONTEND_DIR / 'static']

# Media files (user uploads like profile pictures)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Email Configuration ─────────────────────────────────────────────────────
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'mediskinai@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'MediSkin AI <{EMAIL_HOST_USER}>')

_real_password = EMAIL_HOST_PASSWORD and EMAIL_HOST_PASSWORD not in ('', '[PASSWORD]', 'your_app_password_here')

if _real_password:
    # Production / real Gmail SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    # Development fallback — emails print to the runserver terminal
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ─── Authentication Backends ──────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    # Standard Django auth (username + password)
    'django.contrib.auth.backends.ModelBackend',
    # allauth specific auth (Google OAuth etc.)
    'allauth.account.auth_backends.AuthenticationBackend',
]


# ─── django-allauth — Google OAuth 2.0 ───────────────────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/auth/google/complete/'   # after successful Google OAuth
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'

# Account settings (allauth 0.65+ syntax)
ACCOUNT_EMAIL_VERIFICATION = 'none'   # skip email verification for social login
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # allow login via username or email
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # required signup fields

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True               # auto-sign-up for new social users
SOCIALACCOUNT_EMAIL_REQUIRED = False           # don't require email on social signup
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True      # allow email-based account matching
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # auto-connect Google to existing account with same email
SOCIALACCOUNT_LOGIN_ON_GET = True              # allow GET-based OAuth initiation
SOCIALACCOUNT_STORE_TOKENS = False             # don't store OAuth tokens in DB

# Custom adapters — bypass the /accounts/3rdparty/signup/ confirmation page entirely
SOCIALACCOUNT_ADAPTER = 'main.adapters.NoSignupFormSocialAdapter'
ACCOUNT_ADAPTER     = 'main.adapters.NoSignupFormAccountAdapter'


# NOTE: Google client_id & secret are stored in the DB (SocialApp record, id=1).
# Do NOT add an 'APP' key here — that would create a second app and cause
# MultipleObjectsReturned when allauth tries to look up the provider.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

# ── Google Maps Platform ───────────────────────────────────────────────────────
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# ── API Base URL (injected into templates so JS can make cross-origin API calls)
# Leave empty in development (JS uses relative URLs like /api/predict/)
# Set to your Render service URL in production, e.g.:
#   API_BASE_URL=https://mediskin-backend.onrender.com
API_BASE_URL = os.environ.get('API_BASE_URL', '')


# ─── CORS Configuration ────────────────────────────────────────────────────────
# Enable cross-origin requests from frontend (Vercel, local dev, custom domains)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',      # Local React/Next.js dev
    'http://127.0.0.1:5173',      # Local frontend dev
    'http://localhost:8000',      # Local Django dev
]

# For production, add more origins via environment variable
if os.environ.get('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS.extend(
        [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')]
    )

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
